# fly.toml app configuration file generated for polymarket-bot-02 on 2026-05-03T21:50:34+01:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'polymarket-bot-02'
primary_region = 'ams'

[build]

[env]
  PORT = '8088'

[http_service]
  internal_port = 8088
  force_https = true
  auto_start_machines = true
  auto_stop_machines = false
  min_machines_running = 1
  processes = ['app']

  [http_service.concurrency]
    type = 'connections'
    hard_limit = 25
    soft_limit = 20

[[vm]]
  memory = '256mb'
  cpu_kind = 'shared'
  cpus = 1
