package polymarket

import (
	"bytes"
	"context"
	"crypto/ecdsa"
	"crypto/hmac"
	cryptorand "crypto/rand"
	"crypto/sha256"
	"encoding/base64"
	"encoding/binary"
	"encoding/hex"
	"encoding/json"
	"fmt"
	"io"
	"log/slog"
	"math"
	"math/big"
	"net/http"
	"strconv"
	"strings"
	"time"

	"github.com/ethereum/go-ethereum/common"
	"github.com/ethereum/go-ethereum/crypto"
)

// Signature type constants — must match what Polymarket expects.
const (
	SigTypeEOA        = 0 // standalone EOA wallet (MetaMask self-custody, no proxy)
	SigTypePolyProxy  = 1 // Magic Link / email / Telegram social login
	SigTypeGnosisSafe = 2 // browser wallet (MetaMask/Rabby) or Privy/Turnkey embedded wallet
	SigTypePoly1271   = 3 // ERC-1271 smart contract wallet — deposit wallet flow (new API users)
)

// V2 Exchange contract on Polygon mainnet (changed from V1 in the April 2026 upgrade).
const exchangeV2Contract = "0xE111180000d2663C0091e4f400237545B87B996B"

// V2 EIP-712 Order type string.  Fields dropped from V1: taker, expiration, nonce, feeRateBps.
// Fields added in V2: timestamp, metadata, builder.
const orderTypeString = "Order(uint256 salt,address maker,address signer,uint256 tokenId," +
	"uint256 makerAmount,uint256 takerAmount,uint8 side,uint8 signatureType," +
	"uint256 timestamp,bytes32 metadata,bytes32 builder)"

// poly1271TypeString is the EIP-712 TypedDataSign wrapper type used for POLY_1271 (ERC-7739).
// The signer signs a TypedDataSign struct (under the CTF Exchange V2 domain) that contains
// the Order struct hash plus the deposit wallet's own EIP-712 domain fields.
const poly1271TypeString = "TypedDataSign(Order contents,string name,string version," +
	"uint256 chainId,address verifyingContract,bytes32 salt)" +
	"Order(uint256 salt,address maker,address signer,uint256 tokenId," +
	"uint256 makerAmount,uint256 takerAmount,uint8 side,uint8 signatureType," +
	"uint256 timestamp,bytes32 metadata,bytes32 builder)"

const (
	defaultTickSize         = 0.01
	maxBinaryBuyPrice       = 0.99
	collateralScale         = 1_000_000
	marketBuyMakerPrecision = 10_000 // 2 decimals in 6-decimal fixed units
	marketBuyTakerPrecision = 100    // 4 decimals in 6-decimal fixed units
)

// TraderConfig holds all credentials needed for live order placement.
type TraderConfig struct {
	// PrivateKeyHex is the 0x-prefixed EOA private key exported from reveal.magic.link/polymarket.
	PrivateKeyHex string
	// ProxyWallet is the 0x-prefixed account funder address.
	// For POLY_1271, this is the deposit wallet used as both maker and signer.
	ProxyWallet string
	// APIKey / APISecret / APIPassphrase are generated by scripts/gen-api-keys.mjs.
	APIKey        string
	APISecret     string // base64-encoded
	APIPassphrase string
	// SignatureType: 1=POLY_PROXY (Telegram/email/Google), 2=GNOSIS_SAFE (browser wallet),
	// 3=POLY_1271 (deposit wallet — required for new API users).
	SignatureType int
}

// OrderResult is returned by PlaceMarketOrder.
type OrderResult struct {
	OrderID      string `json:"orderID"`
	Status       string `json:"status"`
	MakingAmount string `json:"makingAmount,omitempty"`
	TakingAmount string `json:"takingAmount,omitempty"`
	ErrorMsg     string `json:"error,omitempty"`
}

// OrderStatus is returned by GetOrderStatus.
type OrderStatus struct {
	ID     string `json:"id"`
	Status string `json:"status"` // "live" | "matched" | "cancelled"

	// Legacy/order response fields: collateral amounts in 6-decimal pUSD units.
	MakerAmount       string `json:"makerAmount"`
	MakerAmountFilled string `json:"makerAmountFilled"`

	// Legacy/order response fields: outcome token amounts in 6-decimal units.
	TakerAmount       string `json:"takerAmount"`
	TakerAmountFilled string `json:"takerAmountFilled"`

	// /data/order fields returned by current CLOB clients.
	OriginalSize string `json:"original_size"`
	SizeMatched  string `json:"size_matched"`
	Price        string `json:"price"`
}

// FilledUSD returns the actual USD spent on this order (0 if unfilled).
func (s *OrderStatus) FilledUSD() float64 {
	if s.MakerAmountFilled != "" {
		n, _ := strconv.ParseFloat(s.MakerAmountFilled, 64)
		return n / collateralScale
	}
	shares, price := s.FilledShares(), s.FillPrice()
	return shares * price
}

// FilledShares returns the actual outcome-token shares received (0 if unfilled).
func (s *OrderStatus) FilledShares() float64 {
	if s.TakerAmountFilled != "" {
		n, _ := strconv.ParseFloat(s.TakerAmountFilled, 64)
		return n / collateralScale
	}
	n, _ := strconv.ParseFloat(s.SizeMatched, 64)
	return n / collateralScale
}

// FillPrice returns the actual average fill price (0 if unfilled).
func (s *OrderStatus) FillPrice() float64 {
	if s.Price != "" {
		price, _ := strconv.ParseFloat(s.Price, 64)
		return price
	}
	maker, _ := strconv.ParseFloat(s.MakerAmountFilled, 64)
	taker, _ := strconv.ParseFloat(s.TakerAmountFilled, 64)
	if taker == 0 {
		return 0
	}
	return maker / taker
}

func (s *OrderStatus) normalize() {
	switch s.Status {
	case "ORDER_STATUS_LIVE":
		s.Status = "live"
	case "ORDER_STATUS_MATCHED":
		s.Status = "matched"
	case "ORDER_STATUS_CANCELED", "ORDER_STATUS_CANCELED_MARKET_RESOLVED", "ORDER_STATUS_INVALID":
		s.Status = "cancelled"
	}
}

// Trader places live FOK market orders on Polymarket CLOB V2.
type Trader struct {
	config     TraderConfig
	httpClient *http.Client
	privateKey *ecdsa.PrivateKey
	eoaAddress common.Address

	// Pre-computed EIP-712 values.
	orderTypeHash    []byte
	domainSeparator  []byte
	poly1271TypeHash []byte // TypedDataSign type hash for POLY_1271 (ERC-7739)
}

// NewTrader validates the config and returns a ready-to-use Trader.
func NewTrader(config TraderConfig) (*Trader, error) {
	hexKey := strings.TrimPrefix(config.PrivateKeyHex, "0x")
	pk, err := crypto.HexToECDSA(hexKey)
	if err != nil {
		return nil, fmt.Errorf("invalid POLYMARKET_PRIVATE_KEY: %w", err)
	}

	if !strings.HasPrefix(config.ProxyWallet, "0x") {
		return nil, fmt.Errorf("POLYMARKET_PROXY_WALLET must start with 0x")
	}
	if config.APIKey == "" || config.APISecret == "" || config.APIPassphrase == "" {
		return nil, fmt.Errorf("POLYMARKET_API_KEY, POLYMARKET_API_SECRET and POLYMARKET_API_PASSPHRASE must all be set")
	}

	t := &Trader{
		config:     config,
		httpClient: NewHTTPClientWithProxy(10 * time.Second),
		privateKey: pk,
		eoaAddress: crypto.PubkeyToAddress(pk.PublicKey),
	}
	t.orderTypeHash = crypto.Keccak256([]byte(orderTypeString))
	t.domainSeparator = t.buildDomainSeparator()
	t.poly1271TypeHash = crypto.Keccak256([]byte(poly1271TypeString))
	return t, nil
}

// EOAAddress returns the public address derived from the private key.
func (t *Trader) EOAAddress() string { return t.eoaAddress.Hex() }

// PlaceMarketOrder submits a FAK (Fill and Kill) market buy order on CLOB V2.
//
//   - tokenID     – outcome token to buy (decimal string from Polymarket's clobTokenIds)
//   - amountUSD   – pUSD to spend (e.g. 10.0 for $10)
//   - entryPrice  – current best ask (0–1); used to calculate minimum acceptable shares
func (t *Trader) PlaceMarketOrder(ctx context.Context, tokenID string, amountUSD, entryPrice float64) (*OrderResult, error) {
	if entryPrice <= 0 || entryPrice >= 1 {
		return nil, fmt.Errorf("entry price %f out of range (0,1)", entryPrice)
	}

	tokenIDBig, ok := new(big.Int).SetString(tokenID, 10)
	if !ok {
		return nil, fmt.Errorf("cannot parse tokenID %q as decimal integer", tokenID)
	}

	makerAmount, takerAmount, err := marketBuyAmounts(amountUSD, entryPrice)
	if err != nil {
		return nil, err
	}

	salt := randomSalt()
	tsMs := new(big.Int).SetInt64(time.Now().UnixMilli())

	// For POLY_1271, both maker and signer must be the deposit wallet address.
	// For all other sig types, maker = proxy/funder wallet, signer = EOA.
	var makerAddr, signerAddr common.Address
	makerAddr = common.HexToAddress(t.config.ProxyWallet)
	if t.config.SignatureType == SigTypePoly1271 {
		signerAddr = makerAddr
	} else {
		signerAddr = t.eoaAddress
	}

	order := &v2Order{
		Salt:          salt,
		Maker:         makerAddr,
		Signer:        signerAddr,
		TokenID:       tokenIDBig,
		MakerAmount:   new(big.Int).SetInt64(makerAmount),
		TakerAmount:   new(big.Int).SetInt64(takerAmount),
		Side:          0, // BUY
		SignatureType: uint8(t.config.SignatureType),
		Timestamp:     tsMs,
		Metadata:      [32]byte{},
		Builder:       [32]byte{},
	}

	var sig string
	if t.config.SignatureType == SigTypePoly1271 {
		sig, err = t.signOrderPoly1271(order)
	} else {
		sig, err = t.signOrder(order)
	}
	if err != nil {
		return nil, fmt.Errorf("sign order: %w", err)
	}

	zeros32 := "0x" + strings.Repeat("00", 32)
	reqBody := postOrderBody{
		Order: orderWireBody{
			Salt:          json.Number(salt.String()),
			Maker:         order.Maker.Hex(),
			Signer:        order.Signer.Hex(),
			TokenID:       tokenID,
			MakerAmount:   order.MakerAmount.String(),
			TakerAmount:   order.TakerAmount.String(),
			Expiration:    "0",
			Side:          "BUY",
			SignatureType: t.config.SignatureType,
			Timestamp:     tsMs.String(),
			Metadata:      zeros32,
			Builder:       zeros32,
			Signature:     sig,
		},
		Owner:     t.config.APIKey,
		OrderType: "FAK",
		DeferExec: false,
		PostOnly:  false,
	}

	bodyJSON, err := json.Marshal(reqBody)
	if err != nil {
		return nil, fmt.Errorf("marshal order body: %w", err)
	}
	payload := string(bodyJSON)
	slog.InfoContext(ctx, "clob order payload",
		"payload", payload,
		"entryPrice", entryPrice,
		"limitPrice", float64(makerAmount)/float64(takerAmount),
		"amountUSD", amountUSD)

	path := "/order"
	headers := t.l2AuthHeaders("POST", path, payload)

	req, err := http.NewRequestWithContext(ctx, http.MethodPost, clobBaseURL+path, bytes.NewReader(bodyJSON))
	if err != nil {
		return nil, fmt.Errorf("create request: %w", err)
	}
	req.Header.Set("Content-Type", "application/json")
	for k, v := range headers {
		req.Header.Set(k, v)
	}

	resp, err := t.httpClient.Do(req)
	if err != nil {
		return nil, fmt.Errorf("POST /order: %w", err)
	}
	defer resp.Body.Close()
	respBytes, _ := io.ReadAll(resp.Body)

	var result OrderResult
	_ = json.Unmarshal(respBytes, &result)

	if resp.StatusCode != http.StatusOK && resp.StatusCode != http.StatusCreated {
		slog.ErrorContext(ctx, "clob order rejected",
			"status", resp.StatusCode,
			"response", string(respBytes),
			"payload", payload)
		return &result, fmt.Errorf("CLOB %d: %s", resp.StatusCode, string(respBytes))
	}
	return &result, nil
}

func marketBuyAmounts(amountUSD, entryPrice float64) (int64, int64, error) {
	if amountUSD <= 0 {
		return 0, 0, fmt.Errorf("amountUSD %f must be positive", amountUSD)
	}

	// Market buys are still limit orders: price is the worst acceptable fill.
	// BTC 5m markets normally trade on a 1c tick, so keep the signed ratio on-tick
	// and never submit the invalid $1.00 binary-token price.
	worstPrice := math.Ceil(entryPrice*1.05/defaultTickSize) * defaultTickSize
	if worstPrice > maxBinaryBuyPrice {
		worstPrice = maxBinaryBuyPrice
	}
	if worstPrice < defaultTickSize {
		worstPrice = defaultTickSize
	}

	priceTicks := int64(math.Round(worstPrice / defaultTickSize))
	tickUnits := int64(math.Round(1 / defaultTickSize))
	if priceTicks <= 0 || tickUnits <= 0 || priceTicks >= tickUnits {
		return 0, 0, fmt.Errorf("worst price %.4f cannot be represented on tick %.4f", worstPrice, defaultTickSize)
	}

	makerAmount := roundDownFixed(amountUSD, collateralScale, marketBuyMakerPrecision)
	if makerAmount <= 0 {
		return 0, 0, fmt.Errorf("amountUSD %.6f too small for market buy precision", amountUSD)
	}

	// Market buys are validated separately by the CLOB: maker collateral can
	// only use cents, while taker outcome shares can use 4 decimals.
	rawTakerAmount := float64(makerAmount) * float64(tickUnits) / float64(priceTicks)
	takerAmount := roundDownInt(rawTakerAmount, marketBuyTakerPrecision)
	if takerAmount <= 0 {
		return 0, 0, fmt.Errorf("amountUSD %.6f too small for price %.4f", amountUSD, worstPrice)
	}
	return makerAmount, takerAmount, nil
}

func roundDownFixed(amount float64, scale, precision int64) int64 {
	units := int64(math.Floor(amount*float64(scale) + 1e-9))
	return roundDownInt(float64(units), precision)
}

func roundDownInt(amount float64, precision int64) int64 {
	units := int64(math.Floor(amount + 1e-9))
	return units - units%precision
}

// GetOrderStatus fetches the current status of an order from CLOB V2.
// FAK orders settle within milliseconds; call this after a short delay.
func (t *Trader) GetOrderStatus(ctx context.Context, orderID string) (*OrderStatus, error) {
	path := "/data/order/" + orderID
	headers := t.l2AuthHeaders("GET", path, "")

	req, err := http.NewRequestWithContext(ctx, http.MethodGet, clobBaseURL+path, nil)
	if err != nil {
		return nil, fmt.Errorf("create request: %w", err)
	}
	for k, v := range headers {
		req.Header.Set(k, v)
	}

	resp, err := t.httpClient.Do(req)
	if err != nil {
		return nil, fmt.Errorf("GET /order: %w", err)
	}
	defer resp.Body.Close()
	body, _ := io.ReadAll(resp.Body)

	if resp.StatusCode != http.StatusOK {
		return nil, fmt.Errorf("CLOB %d: %s", resp.StatusCode, string(body))
	}

	var status OrderStatus
	if err := json.Unmarshal(body, &status); err != nil {
		return nil, fmt.Errorf("decode order status: %w", err)
	}
	status.normalize()
	return &status, nil
}

// ── EIP-712 signing ────────────────────────────────────────────────────────────

type v2Order struct {
	Salt          *big.Int
	Maker         common.Address
	Signer        common.Address
	TokenID       *big.Int
	MakerAmount   *big.Int
	TakerAmount   *big.Int
	Side          uint8
	SignatureType uint8
	Timestamp     *big.Int
	Metadata      [32]byte
	Builder       [32]byte
}

func (t *Trader) buildDomainSeparator() []byte {
	domainTypeHash := crypto.Keccak256([]byte(
		"EIP712Domain(string name,string version,uint256 chainId,address verifyingContract)"))
	name := crypto.Keccak256([]byte("Polymarket CTF Exchange"))
	version := crypto.Keccak256([]byte("2"))
	chainID := padUint256(big.NewInt(137))
	contract := padAddr(common.HexToAddress(exchangeV2Contract))

	enc := concat(domainTypeHash, name, version, chainID, contract)
	return crypto.Keccak256(enc)
}

func (t *Trader) structHash(o *v2Order) []byte {
	enc := concat(
		t.orderTypeHash,
		padUint256(o.Salt),
		padAddr(o.Maker),
		padAddr(o.Signer),
		padUint256(o.TokenID),
		padUint256(o.MakerAmount),
		padUint256(o.TakerAmount),
		padUint8(o.Side),
		padUint8(o.SignatureType),
		padUint256(o.Timestamp),
		o.Metadata[:],
		o.Builder[:],
	)
	return crypto.Keccak256(enc)
}

func (t *Trader) signOrder(o *v2Order) (string, error) {
	digest := crypto.Keccak256(
		[]byte("\x19\x01"),
		t.domainSeparator,
		t.structHash(o),
	)
	sig, err := crypto.Sign(digest, t.privateKey)
	if err != nil {
		return "", err
	}
	sig[64] += 27 // Ethereum v adjustment (recovery id → v)
	return "0x" + hex.EncodeToString(sig), nil
}

// signOrderPoly1271 produces a POLY_1271 (ERC-7739) signature for deposit wallet orders.
//
// The format matches @polymarket/clob-client-v2's ExchangeOrderBuilderV2.buildOrderSignature:
//
//	innerSig (65 bytes) | appDomainSep (32 bytes) | contentsHash (32 bytes) | orderTypeString (bytes) | uint16BE(len) (2 bytes)
//
// The innerSig is an ECDSA signature of:
//
//	keccak256("\x19\x01" || CTFExchangeV2Domain || TypedDataSignStructHash)
//
// where TypedDataSignStructHash = keccak256(poly1271TypeHash || contentsHash || keccak256("DepositWallet") || keccak256("1") || chainId || depositWallet || bytes32(0)).
func (t *Trader) signOrderPoly1271(o *v2Order) (string, error) {
	depositWallet := common.HexToAddress(t.config.ProxyWallet)

	// contentsHash = EIP-712 struct hash of the Order (identical to the regular order hash).
	contentsHash := t.structHash(o)

	// TypedDataSign struct hash binds the order to the deposit wallet's EIP-712 domain.
	typedDataSignStructHash := crypto.Keccak256(concat(
		t.poly1271TypeHash,
		contentsHash,
		crypto.Keccak256([]byte("DepositWallet")),
		crypto.Keccak256([]byte("1")),
		padUint256(big.NewInt(137)),
		padAddr(depositWallet),
		make([]byte, 32), // bytes32(0) salt
	))

	// Inner digest: sign under the CTF Exchange V2 domain (same as regular orders).
	innerDigest := crypto.Keccak256(concat(
		[]byte("\x19\x01"),
		t.domainSeparator,
		typedDataSignStructHash,
	))

	innerSig, err := crypto.Sign(innerDigest, t.privateKey)
	if err != nil {
		return "", err
	}
	innerSig[64] += 27

	// Build the full POLY_1271 signature bytes consumed by the deposit wallet's isValidSignature.
	typeStringBytes := []byte(orderTypeString)
	lenBytes := make([]byte, 2)
	binary.BigEndian.PutUint16(lenBytes, uint16(len(typeStringBytes)))

	var buf bytes.Buffer
	buf.Write(innerSig)          // 65 bytes: ECDSA signature of innerDigest
	buf.Write(t.domainSeparator) // 32 bytes: CTF Exchange V2 domain separator (appDomainSep)
	buf.Write(contentsHash)      // 32 bytes: order struct hash
	buf.Write(typeStringBytes)   // variable: Order type string as UTF-8 bytes
	buf.Write(lenBytes)          // 2 bytes: big-endian uint16 length of type string

	return "0x" + hex.EncodeToString(buf.Bytes()), nil
}

// ── L2 HMAC authentication headers ───────────────────────────────────────────

func (t *Trader) l2AuthHeaders(method, path, body string) map[string]string {
	ts := strconv.FormatInt(time.Now().Unix(), 10)
	sig := buildL2Signature(t.config.APISecret, ts, method, path, body)

	// POLY_ADDRESS is the Polygon address that the API key was derived for.
	// For type 0 (EOA) and type 3 (POLY_1271 deposit wallet), the API key is
	// tied to the EOA that owns the wallet. For types 1/2, earlier Polymarket
	// docs suggested using the proxy/funder address, but CLOB V2 enforces that
	// the order signer address must match the API key address. Since our order
	// signer is always the EOA (the only key we have), POLY_ADDRESS must be the
	// EOA for all types when the API key was generated against the EOA.
	polyAddress := t.eoaAddress.Hex()
	if t.config.SignatureType == SigTypePolyProxy {
		// Keep legacy behavior for POLY_PROXY only if the user explicitly
		// generated the API key against the proxy address.
		polyAddress = t.config.ProxyWallet
	}

	return map[string]string{
		"POLY_ADDRESS":    polyAddress,
		"POLY_SIGNATURE":  sig,
		"POLY_TIMESTAMP":  ts,
		"POLY_API_KEY":    t.config.APIKey,
		"POLY_PASSPHRASE": t.config.APIPassphrase,
	}
}

func buildL2Signature(secret, timestamp, method, path, body string) string {
	message := timestamp + method + path + body

	// Polymarket API secrets and HMAC signatures use URL-safe base64.
	secretBytes, err := decodeBase64URL(secret)
	if err != nil {
		secretBytes = []byte(secret)
	}
	mac := hmac.New(sha256.New, secretBytes)
	mac.Write([]byte(message))
	return base64.URLEncoding.EncodeToString(mac.Sum(nil))
}

func decodeBase64URL(s string) ([]byte, error) {
	if decoded, err := base64.URLEncoding.DecodeString(s); err == nil {
		return decoded, nil
	}
	if decoded, err := base64.RawURLEncoding.DecodeString(s); err == nil {
		return decoded, nil
	}
	if decoded, err := base64.StdEncoding.DecodeString(s); err == nil {
		return decoded, nil
	}
	return base64.RawStdEncoding.DecodeString(s)
}

// ── Wire body types ───────────────────────────────────────────────────────────

type orderWireBody struct {
	Salt          json.Number `json:"salt"`
	Maker         string      `json:"maker"`
	Signer        string      `json:"signer"`
	TokenID       string      `json:"tokenId"`
	MakerAmount   string      `json:"makerAmount"`
	TakerAmount   string      `json:"takerAmount"`
	Expiration    string      `json:"expiration"`
	Side          string      `json:"side"`
	SignatureType int         `json:"signatureType"`
	Timestamp     string      `json:"timestamp"`
	Metadata      string      `json:"metadata"`
	Builder       string      `json:"builder"`
	Signature     string      `json:"signature"`
}

type postOrderBody struct {
	Order     orderWireBody `json:"order"`
	Owner     string        `json:"owner"`     // API key
	OrderType string        `json:"orderType"` // "FOK"
	DeferExec bool          `json:"deferExec"`
	PostOnly  bool          `json:"postOnly"`
}

// ── ABI encoding helpers ──────────────────────────────────────────────────────

// padUint256 encodes n as a 32-byte big-endian value.
func padUint256(n *big.Int) []byte {
	b := n.Bytes()
	out := make([]byte, 32)
	copy(out[32-len(b):], b)
	return out
}

// padAddr encodes an Ethereum address right-justified in 32 bytes.
func padAddr(a common.Address) []byte {
	out := make([]byte, 32)
	copy(out[12:], a.Bytes())
	return out
}

// padUint8 encodes a uint8 right-justified in 32 bytes.
func padUint8(n uint8) []byte {
	out := make([]byte, 32)
	out[31] = n
	return out
}

// concat joins byte slices without intermediate allocations.
func concat(slices ...[]byte) []byte {
	total := 0
	for _, s := range slices {
		total += len(s)
	}
	out := make([]byte, 0, total)
	for _, s := range slices {
		out = append(out, s...)
	}
	return out
}

// randomSalt generates a random salt that fits inside JavaScript's
// Number.MAX_SAFE_INTEGER (2^53 - 1). The CLOB API parses salt as a JSON
// number; anything larger silently loses precision server-side and the
// reconstructed EIP-712 digest no longer matches our signature.
// Matches py-clob-client / clob-client which use round(random() * 1e9).
func randomSalt() *big.Int {
	const maxSafe = 1 << 53 // 2^53; well below the 2^53-1 ceiling
	max := new(big.Int).SetUint64(maxSafe)
	n, err := cryptorand.Int(cryptorand.Reader, max)
	if err != nil {
		return new(big.Int).SetInt64(time.Now().UnixNano() & (maxSafe - 1))
	}
	return n
}
